version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before-deploy.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu